---
title: "Indicator Summary"
author: "Vincent Woolsey"
date: "5/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#install.packages("tidyverse")
#install.packages("ggpubr")
#install.packages("janitor")
library(tidyverse)
library(ggpubr)
library(janitor)
library(ggplot2)
library(viridis)
library(hrbrthemes)
```



```{r}
Indicator_Data <- read.csv(file = "Indicator_data.csv")
#View(Indicator_Data)
Indicator_Data
```


```{r}
ID_data <- Indicator_Data %>%
  select(Indicator.Type..Column.Name., Physical, X, X.1, Biological.Indicators, X.2, X.3, X.4, X.5, X.6, X.7, X.8, X.9, Chemical) %>%
  row_to_names(row_number = 1)
  

ID_data <- ID_data[-c(9,10,11), ]
#view(ID_data)

ID_tidy <- pivot_longer(ID_data, cols = 2:14, names_to ="Indicator Groups", values_to = "Frequency of Use")
ID_tidy_df <- data.frame(ID_tidy)

ID_tidy_df$Frequency.of.Use <- as.numeric(ID_tidy_df$Frequency.of.Use)

#view(ID_tidy_df)

```


```{r}
ID_tidy_df$Indicator.Groups <- factor(ID_tidy_df$Indicator.Groups, levels = c("Hydrology", "Topography", "Soils", "Vegetation Cover", "Vegetation Species Diversity", "Vegetative Growth and Health","Non-native Species", "Birds", "Fish", "Invertebrates", "Other Fauna (mammals, reptiles, etc.)", "Endangered Species Metrics (By Species)", "Water Quality"))

box_fills <- c("red", "red3", "red4", "seagreen1", "seagreen2", "seagreen3", "seagreen4", "sienna1", "sienna2", "sienna3", "sienna","sienna4", "deepskyblue")

ggplot(data = ID_tidy_df, aes(x = Indicator.Group..Column.Name., y = Frequency.of.Use, fill = Indicator.Groups)) +
 geom_bar(stat = "identity", width = 0.75, position = "stack",  color = "black") + 
  coord_flip() + 
  scale_fill_manual(values = box_fills, guide = "none") +
 labs(x = "\n Restored Wetlands", y = "Total Indicators Used \n", title = "Indicator Use Frequency in Restored Wetlands \n") +
 theme(plot.title = element_text(hjust = 0.5), 
 axis.title.x = element_text(face="bold", colour="red", size = 12),
 axis.title.y = element_text(face="bold", colour="red", size = 12))
```


```{r}
ggsave("./Figures/Community/nMDS_all_strata_speciesID.tiff", 
           nMDS.plot.all,
           dpi = 150)

```


